name: tofu-output
description: Set the action outputs from OpenTofu configuration outputs
author: Daniel Flook

inputs:
  path:
    description: Path to the OpenTofu configuration
    required: false
    default: .
  workspace:
    description: Name of the OpenTofu workspace
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""

runs:
  env:
    OPENTOFU: true
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:b118825cdb351b48e6dff986984013d1343cd5aace36fcdf457528cf01954f40
  entrypoint: /entrypoints/output.sh

branding:
  icon: globe
  color: purple
