name: tofu-output
description: Set the action outputs from OpenTofu configuration outputs
author: Daniel Flook

inputs:
  path:
    description: Path to the OpenTofu configuration
    required: false
    default: .
  workspace:
    description: Name of the OpenTofu workspace
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""

runs:
  env:
    OPENTOFU: true
  using: docker
  image: docker://ghcr.io/dflook/terraform-github-actions@sha256:2fa1462c0d719834b0dd18acf08914e306405b8d8538adb1b4db8ef940dfe6ba
  entrypoint: /entrypoints/output.sh

branding:
  icon: globe
  color: purple
